version: "3.8"

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env

  web:
    image: knoort/foodgram:v1
    build: .
    volumes:
      - static:/code/static
      - ./media:/code/media
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - static:/static
      - ./media:/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - '80:8080'
    depends_on:
      - web
